In [12]:
import numpy as np
import heapq

# Define the goal state (Reverse Order)
GOAL_STATE = np.array([
    [8, 7, 6],
    [5, 4, 3],
    [2, 1, 0]
])

# Goal positions for Manhattan Distance
GOAL_POSITIONS = {
    8: (0, 0),
    7: (0, 1),
    6: (0, 2),
    5: (1, 0),
    4: (1, 1),
    3: (1, 2),
    2: (2, 0),
    1: (2, 1),
    0: (2, 2)
}

# Directions: Up, Down, Left, Right
DIRECTIONS = [(-1, 0), (1, 0), (0, -1), (0, 1)]


class PuzzleState:
    def __init__(self, board, moves=0, previous=None):
        self.board = board
        self.blank_pos = self.find_blank()
        self.moves = moves
        self.previous = previous

    def find_blank(self):
        return tuple(np.argwhere(self.board == 0)[0])

    def is_goal(self):
        return np.array_equal(self.board, GOAL_STATE)

    def get_neighbors(self):
        neighbors = []
        x, y = self.blank_pos

        for dx, dy in DIRECTIONS:
            new_x = x + dx
            new_y = y + dy

            if 0 <= new_x < 3 and 0 <= new_y < 3:
                new_board = self.board.copy()

                # Swap blank with adjacent tile
                new_board[x, y], new_board[new_x, new_y] = (
                    new_board[new_x, new_y],
                    new_board[x, y]
                )

                neighbors.append(
                    PuzzleState(new_board, self.moves + 1, self)
                )

        return neighbors

    def __lt__(self, other):
        return self.moves < other.moves


def heuristic(state):
    """Manhattan Distance Heuristic"""
    distance = 0

    for i in range(3):
        for j in range(3):
            value = state.board[i][j]

            if value != 0:
                goal_x, goal_y = GOAL_POSITIONS[value]
                distance += abs(goal_x - i) + abs(goal_y - j)

    return distance


def a_star(start_state):
    open_set = []
    heapq.heappush(open_set, (heuristic(start_state), start_state))

    closed_set = set()

    while open_set:
        _, current_state = heapq.heappop(open_set)

        if current_state.is_goal():
            return current_state

        closed_set.add(tuple(map(tuple, current_state.board)))

        for neighbor in current_state.get_neighbors():
            board_tuple = tuple(map(tuple, neighbor.board))

            if board_tuple in closed_set:
                continue

            cost = neighbor.moves + heuristic(neighbor)
            heapq.heappush(open_set, (cost, neighbor))

    return None


def print_solution(solution):
    path = []

    while solution:
        path.append(solution.board)
        solution = solution.previous

    path.reverse()

    print("Total Moves:", len(path) - 1)
    print()

    for step, board in enumerate(path):
        print(f"Step {step}:")
        print(board)
        print()


if __name__ == "__main__":

    # Initial State
    initial_state = np.array([
        [3, 1, 2],
        [4, 7, 5],
        [6, 8, 0]
    ])

    start_state = PuzzleState(initial_state)

    solution = a_star(start_state)

    if solution:
        print("Solution Found!\n")
        print_solution(solution)
    else:
        print("No solution found.")

Solution Found!

Total Moves: 28

Step 0:
[[3 1 2]
 [4 7 5]
 [6 8 0]]

Step 1:
[[3 1 2]
 [4 7 0]
 [6 8 5]]

Step 2:
[[3 1 0]
 [4 7 2]
 [6 8 5]]

Step 3:
[[3 0 1]
 [4 7 2]
 [6 8 5]]

Step 4:
[[3 7 1]
 [4 0 2]
 [6 8 5]]

Step 5:
[[3 7 1]
 [4 8 2]
 [6 0 5]]

Step 6:
[[3 7 1]
 [4 8 2]
 [0 6 5]]

Step 7:
[[3 7 1]
 [0 8 2]
 [4 6 5]]

Step 8:
[[3 7 1]
 [8 0 2]
 [4 6 5]]

Step 9:
[[3 7 1]
 [8 6 2]
 [4 0 5]]

Step 10:
[[3 7 1]
 [8 6 2]
 [4 5 0]]

Step 11:
[[3 7 1]
 [8 6 0]
 [4 5 2]]

Step 12:
[[3 7 0]
 [8 6 1]
 [4 5 2]]

Step 13:
[[3 0 7]
 [8 6 1]
 [4 5 2]]

Step 14:
[[0 3 7]
 [8 6 1]
 [4 5 2]]

Step 15:
[[8 3 7]
 [0 6 1]
 [4 5 2]]

Step 16:
[[8 3 7]
 [4 6 1]
 [0 5 2]]

Step 17:
[[8 3 7]
 [4 6 1]
 [5 0 2]]

Step 18:
[[8 3 7]
 [4 6 1]
 [5 2 0]]

Step 19:
[[8 3 7]
 [4 6 0]
 [5 2 1]]

Step 20:
[[8 3 7]
 [4 0 6]
 [5 2 1]]

Step 21:
[[8 0 7]
 [4 3 6]
 [5 2 1]]

Step 22:
[[8 7 0]
 [4 3 6]
 [5 2 1]]

Step 23:
[[8 7 6]
 [4 3 0]
 [5 2 1]]

Step 24:
[[8 7 6]
 [4 0 3]
 [5 2 1]]

Step 25:
[[8 7 6]
 [0 4 3]