In [ ]:
import numpy as np

GOAL_STATE = np.array([
    [8,7,6],
    [5,4,3],
    [2,1,0]
])

GOAL_POSITIONS = {
    8:(0,0),7:(0,1),6:(0,2),
    5:(1,0),4:(1,1),3:(1,2),
    2:(2,0),1:(2,1),0:(2,2)
}

MOVES = {
    "UP":(-1,0),
    "DOWN":(1,0),
    "LEFT":(0,-1),
    "RIGHT":(0,1)
}

def heuristic(board):
    dist = 0
    for i in range(3):
        for j in range(3):
            val = board[i][j]
            if val != 0:
                gx, gy = GOAL_POSITIONS[val]
                dist += abs(i-gx) + abs(j-gy)
    return dist

def suggest_move(board):
    x, y = np.argwhere(board == 0)[0]

    best_move = None
    best_score = float('inf')

    for move, (dx, dy) in MOVES.items():
        nx, ny = x+dx, y+dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            temp = board.copy()
            temp[x,y], temp[nx,ny] = temp[nx,ny], temp[x,y]

            score = heuristic(temp)

            if score < best_score:
                best_score = score
                best_move = move

    return best_move

def make_move(board, move):
    x, y = np.argwhere(board == 0)[0]

    if move not in MOVES:
        return board

    dx, dy = MOVES[move]
    nx, ny = x+dx, y+dy

    if 0 <= nx < 3 and 0 <= ny < 3:
        board = board.copy()
        board[x,y], board[nx,ny] = board[nx,ny], board[x,y]

    return board

# Initial board
board = np.array([
    [3,1,2],
    [4,7,5],
    [6,8,0]
])

while True:

    print("\nCurrent Board:")
    print(board)

    if np.array_equal(board, GOAL_STATE):
        print("Congratulations! Puzzle Solved.")
        break

    choice = input("\nEnter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit: ").upper()

    if choice == "Q":
        break

    elif choice == "H":
        hint = suggest_move(board)
        print("AI Suggestion:", hint)
        # Board is NOT changed

    elif choice in MOVES:
        board = make_move(board, choice)

    else:
        print("Invalid Input")


Current Board:
[[3 1 2]
 [4 7 5]
 [6 8 0]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 5]
 [6 8 0]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  up



Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  up



Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: DOWN

Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  down



Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  up



Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: DOWN

Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  down



Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  up



Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: DOWN

Current Board:
[[3 1 0]
 [4 7 2]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  down



Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  h


AI Suggestion: UP

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]



Enter move (UP/DOWN/LEFT/RIGHT), H for Hint, Q to Quit:  


Invalid Input

Current Board:
[[3 1 2]
 [4 7 0]
 [6 8 5]]
