In [43]:
import numpy as np
import random
from time import sleep

#creates empty board
def create_board():
  return np.array(
      [[0, 0, 0],
      [0, 0, 0],
      [0, 0, 0]])

#check for empty spaces on board
def possibilities(board):
    moves = []
    for i in range(3):
        for j in range(3):
            if board[i][j] == 0:
                moves.append(i * 3 + j)
    return moves

#select a random place for the player
def random_place(board, player):
    selection = possibilities(board)

    current_loc = int(input("Enter your move (0-8): "))

    if current_loc not in selection:
        print("Invalid move!")
        return board

    row = current_loc // 3
    col = current_loc % 3

    board[row][col] = player
    return board

#checks whether the player has three of their marks in a horizontal row
def row_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[x][y] != player:
                win = False
                break
        if win:
            return True
    return False

#checks whether the player has three of their marks in a vertical row
def col_win(board, player):
    for x in range(len(board)):
        win = True
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                break
        if win:
            return True
    return False

#checks whether the player has three of their marks in a diagonal row
def diag_win(board, player):
    win = True
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
            break
    if win:
        return True

    win = True
    for x in range(len(board)):
        if board[x, len(board) - 1 - x] != player:
            win = False
            break
    return win

#evaluates whether there is a winner or a tie
def evaluate(board):
    for player in [1, 2]:
        if (row_win(board, player) or
            col_win(board, player) or
            diag_win(board, player)):
            return player

    if np.all(board != 0):
        return -1  # tie

    return 0

#main function to start the game
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(1)

    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)

            counter += 1
            winner = evaluate(board)

            if winner != 0:
                return winner

#Driver code
print("Winner is: " +str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Enter your move (0-8):  4


Board after 1 move
[[0 0 0]
 [0 1 0]
 [0 0 0]]


Enter your move (0-8):  3


Board after 2 move
[[0 0 0]
 [2 1 0]
 [0 0 0]]


Enter your move (0-8):  1


Board after 3 move
[[0 1 0]
 [2 1 0]
 [0 0 0]]


Enter your move (0-8):  8


Board after 4 move
[[0 1 0]
 [2 1 0]
 [0 0 2]]


Enter your move (0-8):  7


Board after 5 move
[[0 1 0]
 [2 1 0]
 [0 1 2]]
Winner is: 1
